### ISSUE TITLE
Cannot include partials in layout.html (foundation) unless its also in index.html (view)

### ISSUE THREAD

**Issue by tmcconechy** [stephanepericat/beardcomb#7]
To Reproduce in the Demo folder..
First ren demo and render in a browser, note that in current example the page header is shown twice because its in layout.html and index.html as expected. 

But:

1) Remove  {{>header}} from layout.html and refresh browser - one header shown because its in index.html too, this is as expected.
2) Put it back.
3) Remove {{>header}} from index.html and refresh browser - header is not shown, this is not expected.

So it seems a partial can only render when in the layout if it is also in the index, but this would always mean duplicating content.

**Comment by stephanepericat** [comment]
Hi,

sorry for getting back to you so late. This module is up for an overhaul to work with express 4.
I will address the issues you reported in the process.

Ste

**Comment by stephanepericat** [comment]
fixed in v 0.4.0
